# Generated by Django 5.1.1 on 2024-09-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Concert Name")),
                (
                    "singer_name",
                    models.CharField(max_length=100, verbose_name="Singer Name"),
                ),
                (
                    "length",
                    models.IntegerField(verbose_name="Concert Length (minutes)"),
                ),
                ("date", models.DateTimeField(verbose_name="Concert Date and Time")),
                (
                    "location",
                    models.CharField(max_length=255, verbose_name="Concert Location"),
                ),
                (
                    "available_tickets",
                    models.IntegerField(verbose_name="Available Tickets"),
                ),
                (
                    "ticket_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Ticket Price"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Concert Description"
                    ),
                ),
                (
                    "ticket_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold_out", "Sold Out"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="available",
                        max_length=10,
                        verbose_name="Ticket Status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the location",
                        max_length=100,
                        verbose_name="Location Name",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Enter the full address of the location",
                        max_length=500,
                        verbose_name="Address",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Enter a valid phone number",
                        max_length=11,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        help_text="Maximum capacity of the location",
                        verbose_name="Capacity",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "opening_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Opening Time"
                    ),
                ),
                (
                    "closing_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Closing Time"
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurant"),
                            ("shop", "Shop"),
                            ("service_center", "Service Center"),
                        ],
                        max_length=50,
                        verbose_name="Location Type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
        ),
    ]
