# Generated by Django 5.1.1 on 2024-09-21 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="id",
        ),
        migrations.AddField(
            model_name="location",
            name="IdNumber",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(
                default="iran-Tehran",
                help_text="Enter the full address of the location",
                max_length=500,
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="phone",
            field=models.CharField(
                help_text="Enter a valid phone number",
                max_length=11,
                null=True,
                verbose_name="Phone Number",
            ),
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date_time",
                    models.DateTimeField(verbose_name="Start Date and Time"),
                ),
                (
                    "end_date_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End Date and Time"
                    ),
                ),
                ("seats", models.IntegerField(verbose_name="Number of Seats")),
                (
                    "price_per_seat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Price per Seat",
                    ),
                ),
                (
                    "booked_seats",
                    models.IntegerField(default=0, verbose_name="Booked Seats"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, null=True, verbose_name="Additional Remarks"
                    ),
                ),
                (
                    "concert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="TicketSales.concert",
                        verbose_name="Concert",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="TicketSales.location",
                        verbose_name="Location",
                    ),
                ),
            ],
        ),
    ]
