# Generated by Django 5.1.1 on 2024-09-21 18:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Ticket Price",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ خرید"),
                ),
                (
                    "ticket_code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="کد بلیط"
                    ),
                ),
                (
                    "ticket_status",
                    models.CharField(
                        choices=[
                            ("active", "فعال"),
                            ("expired", "منقضی"),
                            ("canceled", "لغو شده"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="وضعیت بلیط",
                    ),
                ),
                (
                    "reserved_seats",
                    models.IntegerField(
                        default=1, verbose_name="تعداد صندلی\u200cهای رزرو شده"
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ انقضا"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "کارت اعتباری"),
                            ("paypal", "PayPal"),
                            ("cash", "نقدی"),
                        ],
                        max_length=20,
                        verbose_name="نحوه پرداخت",
                    ),
                ),
                (
                    "additional_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات اضافی"
                    ),
                ),
                (
                    "profilemodel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="TicketSales.profile",
                        verbose_name="Profile",
                    ),
                ),
                (
                    "timemodel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="TicketSales.timeslot",
                        verbose_name="TimeSlot",
                    ),
                ),
            ],
        ),
    ]
