# Generated by Django 5.1.1 on 2024-09-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="website",
            field=models.URLField(
                blank=True, default=None, null=True, verbose_name="وب سایت"
            ),
        ),
    ]
