# Generated by Django 5.1.1 on 2024-09-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0002_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="concert",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/",
                verbose_name="عکس پروفایل",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/",
                verbose_name="عکس پروفایل",
            ),
        ),
    ]
