# Generated by Django 5.1.1 on 2024-09-21 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0002_alter_concert_options_alter_concert_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="available_tickets",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="بلیط های موجود",
            ),
        ),
        migrations.AlterField(
            model_name="concert",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات کنسرت"),
        ),
        migrations.AlterField(
            model_name="concert",
            name="ticket_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="قیمت بلیط"
            ),
        ),
        migrations.AlterField(
            model_name="concert",
            name="ticket_status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("sold_out", "Sold Out"),
                    ("cancelled", "Cancelled"),
                ],
                default="available",
                max_length=10,
                verbose_name="وضعیت بلیط",
            ),
        ),
    ]
