# Generated by Django 5.1.1 on 2024-09-21 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0002_remove_location_id_location_idnumber_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="IdNumber",
            new_name="id_number",
        ),
        migrations.AlterField(
            model_name="concert",
            name="available_tickets",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Available Tickets",
            ),
        ),
        migrations.AlterField(
            model_name="concert",
            name="length",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Concert Length (minutes)",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(
                default="Iran-Tehran",
                help_text="Enter the full address of the location",
                max_length=500,
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="capacity",
            field=models.IntegerField(
                help_text="Maximum capacity of the location",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Capacity",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="booked_seats",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Booked Seats",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="seats",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Number of Seats",
            ),
        ),
    ]
