# Generated by Django 5.1.1 on 2024-09-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0002_alter_location_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="website",
            field=models.URLField(
                blank=True,
                choices=[("It does not have a website", "وب سایت ندارد")],
                null=True,
                verbose_name="وب سایت",
            ),
        ),
    ]
