# Generated by Django 5.1.1 on 2024-09-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0003_concert_profile_picture_ticket_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="concert",
            name="profile_picture",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="concert",
            name="Concert_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="Concert_pictures/",
                verbose_name="عکس پروفایل",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="Ticket_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="Ticket_pictures/",
                verbose_name="عکس پروفایل",
            ),
        ),
    ]
