# Generated by Django 5.1.1 on 2024-09-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0003_alter_concert_available_tickets_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="location",
            field=models.CharField(max_length=255, verbose_name="محل برگزاری کنسرت"),
        ),
    ]
