# Generated by Django 5.1.1 on 2024-09-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0003_rename_idnumber_location_id_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="status",
            field=models.CharField(
                choices=[
                    ("Start", "Start"),
                    ("End", "End"),
                    ("Sales", "Sales"),
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="active",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
