# Generated by Django 5.1.1 on 2024-09-25 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0003_alter_location_website"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "مکان", "verbose_name_plural": "مکان\u200cها"},
        ),
        migrations.AddField(
            model_name="location",
            name="website_status",
            field=models.CharField(
                choices=[
                    ("no_website", "وب\u200cسایت ندارد"),
                    ("has_website", "وب\u200cسایت دارد"),
                ],
                default="no_website",
                max_length=20,
                verbose_name="وضعیت وب\u200cسایت",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ],
                verbose_name="عرض جغرافیایی",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180.0),
                    django.core.validators.MaxValueValidator(180.0),
                ],
                verbose_name="طول جغرافیایی",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="phone",
            field=models.CharField(
                help_text="یک شماره تلفن معتبر وارد کنید",
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="شماره تلفن باید ۱۱ رقم باشد", regex="^\\d{11}$"
                    )
                ],
                verbose_name="شماره تلفن",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="وب\u200cسایت"),
        ),
    ]
