# Generated by Django 5.1.1 on 2024-09-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSales', '0004_alter_concert_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='ticket_status',
            field=models.CharField(choices=[('موجود است', 'موجود است'), ('فروخته شد', 'فروخته شد'), ('لغو شد', 'لغو شد')], default='موجود است', max_length=10, verbose_name='وضعیت بلیط'),
        ),
    ]
