# Generated by Django 5.1.1 on 2024-09-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0004_alter_location_options_location_website_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timeslot",
            options={"verbose_name": "سانس", "verbose_name_plural": "سانس"},
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="status",
            field=models.CharField(
                choices=[
                    ("Start", "شروع کنید"),
                    ("End", "پایان"),
                    ("Sales", "فروش"),
                    ("فعال", "فعال"),
                    ("cancelled", "لغو شد"),
                    ("completed", "تکمیل شد"),
                ],
                default="active",
                max_length=10,
                verbose_name="وضعیت",
            ),
        ),
    ]
