# Generated by Django 5.1.1 on 2024-09-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0004_alter_timeslot_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "family",
                    models.CharField(max_length=100, verbose_name="نام خانوادگی"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Man", "مرد"), ("Woman", "زن")],
                        max_length=6,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="آدرس ایمیل"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="شماره تلفن"
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pictures/",
                        verbose_name="عکس پروفایل",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="بیوگرافی")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="آدرس"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ثبت\u200cنام"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین بروزرسانی"
                    ),
                ),
            ],
        ),
    ]
