# Generated by Django 5.1.1 on 2024-09-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0005_alter_timeslot_options_alter_timeslot_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="status",
            field=models.CharField(
                choices=[
                    ("Start", "شروع کنید"),
                    ("End", "پایان"),
                    ("Sales", "فروش"),
                    ("active", "فعال"),
                    ("cancelled", "لغو شد"),
                    ("completed", "تکمیل شد"),
                ],
                default="active",
                max_length=10,
                verbose_name="وضعیت",
            ),
        ),
    ]
