# Generated by Django 5.1.1 on 2024-09-21 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0005_alter_concert_ticket_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="concert",
            options={"verbose_name": "کنسرت", "verbose_name_plural": "کنسرت"},
        ),
    ]
