# Generated by Django 5.1.1 on 2024-09-27 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0006_alter_timeslot_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timeslot",
            options={
                "ordering": ["-start_date_time"],
                "verbose_name": "سانس",
                "verbose_name_plural": "سانس\u200cها",
            },
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="booked_seats",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="صندلی\u200cهای رزرو شده",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="status",
            field=models.CharField(
                choices=[
                    ("start", "شروع کنید"),
                    ("end", "پایان"),
                    ("sales", "فروش"),
                    ("active", "فعال"),
                    ("cancelled", "لغو شد"),
                    ("completed", "تکمیل شد"),
                ],
                default="active",
                max_length=10,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="به\u200cروز شده در"
            ),
        ),
    ]
