# Generated by Django 5.1.1 on 2024-09-27 09:07

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "TicketSales",
            "0007_alter_timeslot_options_alter_timeslot_booked_seats_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timeslot",
            options={
                "ordering": ["-start_date_time", "-end_date_time"],
                "verbose_name": "سانس",
                "verbose_name_plural": "سانس\u200cها",
            },
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="end_date_time",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ و زمان پایان"
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="start_date_time",
            field=django_jalali.db.models.jDateField(verbose_name="تاریخ و زمان شروع"),
        ),
    ]
