# Generated by Django 5.1.1 on 2024-09-22 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "TicketSales",
            "0008_alter_timeslot_booked_seats_alter_timeslot_concert_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timeslot",
            options={"verbose_name": "اسلات زمان", "verbose_name_plural": "اسلات زمان"},
        ),
    ]
