# Generated by Django 5.1.1 on 2024-09-22 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0009_alter_timeslot_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "نمایه", "verbose_name_plural": "نمایه"},
        ),
    ]
