# Generated by Django 5.1.1 on 2024-09-27 09:29

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0009_alter_timeslot_end_date_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="end_date_time",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ و زمان پایان"
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="start_date_time",
            field=django_jalali.db.models.jDateField(verbose_name="تاریخ و زمان شروع"),
        ),
    ]
