# Generated by Django 5.1.1 on 2024-09-22 04:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0010_alter_profile_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"verbose_name": "بلیط", "verbose_name_plural": "بلیط"},
        ),
        migrations.AlterField(
            model_name="ticket",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="قیمت بلیط",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="profilemodel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="TicketSales.profile",
                verbose_name="نمایه",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="timemodel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="TicketSales.timeslot",
                verbose_name="اسلات زمان",
            ),
        ),
    ]
