# Generated by Django 5.1.1 on 2024-09-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0011_alter_ticket_options_alter_ticket_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="name",
            field=models.CharField(max_length=1000, verbose_name="نام"),
        ),
    ]
