# Generated by Django 5.1.1 on 2024-09-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0011_alter_timeslot_end_date_time_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="timeslot",
            name="TicketSales_start_d_2f1a88_idx",
        ),
        migrations.RemoveIndex(
            model_name="timeslot",
            name="TicketSales_status_a4176a_idx",
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="end_date_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ و زمان پایان"
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="price_per_seat",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="قیمت هر صندلی",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="start_date_time",
            field=models.DateTimeField(verbose_name="تاریخ و زمان شروع"),
        ),
    ]
