# Generated by Django 5.1.1 on 2024-09-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicketSales", "0012_alter_ticket_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(
                default="ایران-تهران",
                help_text="آدرس کامل محل را وارد کنید",
                max_length=500,
                verbose_name="آدرس",
            ),
        ),
    ]
