# Generated by Django 5.1.1 on 2024-09-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSales', '0013_alter_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Concert_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Concert_pictures/', verbose_name='عکس پروفایل'),
        ),
    ]
